<?php $stats = $pageData['stats'] ?? []; ?>
<div class="p-4 space-y-4">
    <div class="bg-white rounded-xl p-4 shadow"><h2 class="font-semibold">Admin Analytics Panel</h2><p class="text-xs text-slate-500 mt-1">Jami ko'rsatkichlar, g'oliblar va top talabalar</p></div>
    <div class="grid sm:grid-cols-2 xl:grid-cols-5 gap-4">
        <article class="glass-card rounded-xl shadow-sm p-5"><p class="text-sm text-slate-500">Jami talabalar</p><h2 class="mt-2 text-3xl font-semibold text-slate-900"><?= (int)($stats['students'] ?? 0); ?></h2></article>
        <article class="glass-card rounded-xl shadow-sm p-5"><p class="text-sm text-slate-500">Rezidentlar</p><h2 class="mt-2 text-3xl font-semibold text-slate-900"><?= (int)($stats['residents'] ?? 0); ?></h2></article>
        <article class="glass-card rounded-xl shadow-sm p-5"><p class="text-sm text-slate-500">Kurs o'quvchilar</p><h2 class="mt-2 text-3xl font-semibold text-slate-900"><?= (int)($stats['course_students'] ?? 0); ?></h2></article>
        <article class="glass-card rounded-xl shadow-sm p-5"><p class="text-sm text-slate-500">Mentorlar</p><h2 class="mt-2 text-3xl font-semibold text-slate-900"><?= (int)($stats['mentors'] ?? 0); ?></h2></article>
        <article class="glass-card rounded-xl shadow-sm p-5"><p class="text-sm text-slate-500">Tanlovlar</p><h2 class="mt-2 text-3xl font-semibold text-slate-900"><?= (int)($stats['competitions'] ?? 0); ?></h2></article>
    </div>
    <div class="grid lg:grid-cols-2 gap-4"><section class="bg-white rounded-xl p-4 shadow"><h3 class="font-semibold mb-3">Tanlov natijalari</h3><canvas id="analyticsChart" height="130"></canvas></section><section class="bg-white rounded-xl p-4 shadow"><h3 class="font-semibold mb-3">G'oliblar (1-o'rin)</h3><div class="space-y-2"><?php foreach(($stats['winners'] ?? []) as $idx => $winner): ?><div class="rounded-lg border border-slate-200 px-3 py-2 flex items-center justify-between"><span class="text-sm text-slate-700"><?= ($idx+1); ?>. <?= htmlspecialchars($winner['fio']); ?></span><span class="text-xs px-2 py-1 rounded bg-emerald-100 text-emerald-700"><?= (int)$winner['wins']; ?> g'alaba</span></div><?php endforeach; ?><?php if (empty($stats['winners'])): ?><p class="text-sm text-slate-500">Hozircha g'oliblar yo'q.</p><?php endif; ?></div></section></div>
    <section class="bg-white rounded-xl p-4 shadow"><h3 class="font-semibold mb-3">TOP Talabalar</h3><div class="grid md:grid-cols-2 xl:grid-cols-3 gap-3"><?php foreach(($stats['top_students'] ?? []) as $top): ?><article class="rounded-xl border border-slate-200 p-3 bg-slate-50"><p class="font-medium text-slate-900"><?= htmlspecialchars($top['fio']); ?></p><p class="text-xs text-slate-600 mt-1">Ball: <?= (int)$top['points']; ?> | Natijalar: <?= (int)$top['total_results']; ?></p></article><?php endforeach; ?><?php if (empty($stats['top_students'])): ?><p class="text-sm text-slate-500">Top talabalar topilmadi.</p><?php endif; ?></div></section>
</div>
